apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir
  template:
    metadata:
      labels:
        app: fhir
    spec:
      containers:
        - name: fhir
          image: hapiproject/hapi:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/config/application.yaml
              name: hapi-config
              subPath: application.yaml
      volumes:
        - name: hapi-config
          configMap:
            name: hapi-config
