# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: fhir-service
spec:
  selector:
    app: fhir
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
